export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const HttpStatusText: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/HttpStatusText')['HttpStatusText']
  const TagsProps: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/constants/Tags')['TagsProps']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const clamp: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['clamp']
  const computed: typeof import('vue')['computed']
  const convertDeviceUnit: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/convertDeviceUnit')['convertDeviceUnit']
  const convertImageToBase64: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/convertImageToBase64')['convertImageToBase64']
  const createApp: typeof import('vue')['createApp']
  const createNumberArray: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/createNumberArray')['createNumberArray']
  const createPinia: typeof import('pinia')['createPinia']
  const customRef: typeof import('vue')['customRef']
  const debounce: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/debounce')['default']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const ensure: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['ensure']
  const formatPrice: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['formatPrice']
  const generateSHA256Hash: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/generateSHA256Hash')['generateSHA256Hash']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getBackgroundColor: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getBackgroundColor')['getBackgroundColor']
  const getContrastColor: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getContrastYIQ')['getContrastColor']
  const getContrastYIQBetween2Colors: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getContrastYIQ')['getContrastYIQBetween2Colors']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getImageGroups: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getImageGroups')['getImageGroups']
  const getScale: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getScale')['getScale']
  const getShadowTextColor: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getShadowTextColor')['getShadowTextColor']
  const getText: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getText')['getText']
  const getTextFont: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getTextFont')['getTextFont']
  const h: typeof import('vue')['h']
  const handleImageUpdate: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/handleImageUpdate')['handleImageUpdate']
  const hasOwn: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['hasOwn']
  const inject: typeof import('vue')['inject']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const normalizeString: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['normalizeString']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const orderViews: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/orderViews')['orderViews']
  const paletteFromBase64: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getColorPalette')['paletteFromBase64']
  const parseImagesStep: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/parseImagesStep')['parseImagesStep']
  const parserSteps: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/parsePost')['parserSteps']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const textShadow: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/textShadow')['textShadow']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useApp: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/composables/useApp')['default']
  const useAppState: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/store/app')['useAppState']
  const useAttrs: typeof import('vue')['useAttrs']
  const useBuilderState: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/store/builder')['useBuilderState']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSlots: typeof import('vue')['useSlots']
  const useStep: typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/composables/useStep')['default']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly HttpStatusText: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/HttpStatusText')['HttpStatusText']>
    readonly TagsProps: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/constants/Tags')['TagsProps']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly clamp: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['clamp']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly convertDeviceUnit: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/convertDeviceUnit')['convertDeviceUnit']>
    readonly convertImageToBase64: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/convertImageToBase64')['convertImageToBase64']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createNumberArray: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/createNumberArray')['createNumberArray']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debounce: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/debounce')['default']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly ensure: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['ensure']>
    readonly formatPrice: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['formatPrice']>
    readonly generateSHA256Hash: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/generateSHA256Hash')['generateSHA256Hash']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getBackgroundColor: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getBackgroundColor')['getBackgroundColor']>
    readonly getContrastColor: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getContrastYIQ')['getContrastColor']>
    readonly getContrastYIQBetween2Colors: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getContrastYIQ')['getContrastYIQBetween2Colors']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getImageGroups: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getImageGroups')['getImageGroups']>
    readonly getScale: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getScale')['getScale']>
    readonly getShadowTextColor: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getShadowTextColor')['getShadowTextColor']>
    readonly getText: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getText')['getText']>
    readonly getTextFont: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getTextFont')['getTextFont']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly handleImageUpdate: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/handleImageUpdate')['handleImageUpdate']>
    readonly hasOwn: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['hasOwn']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeString: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/index')['normalizeString']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly orderViews: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/orderViews')['orderViews']>
    readonly paletteFromBase64: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/getColorPalette')['paletteFromBase64']>
    readonly parseImagesStep: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/parseImagesStep')['parseImagesStep']>
    readonly parserSteps: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/parsePost')['parserSteps']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly textShadow: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/utils/textShadow')['textShadow']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useApp: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/composables/useApp')['default']>
    readonly useAppState: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/store/app')['useAppState']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBuilderState: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/store/builder')['useBuilderState']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStep: UnwrapRef<typeof import('/Users/rpkonz/projects/custom_product_js/product-builder/src/composables/useStep')['default']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
